#!/usr/bin/env bash

sudo cp /etc/hosts ~/hosts.new

# Add new entries to ~/hosts.new
echo "127.0.0.2         localhost" | sudo tee -a ~/hosts.new
echo "8.8.8.8           facebook.com" | sudo tee -a ~/hosts.new

# Copy the modified hosts.new file back to /etc/hosts
sudo cp -f ~/hosts.new /etc/hosts
